/**
 * Respuesta de ejemplo de la API (datos ficticios). Es el contenido inicial de la fuente «Leads» (ver js/config.js).
 */
const DATOS_EJEMPLO = [
  {
    "id": "1000000104",
    "email": null,
    "firstname": "Lucía Ramírez",
    "lastname": "",
    "score": 0,
    "stage": "lead",
    "language": null,
    "owner": null,
    "ownerTeam": null,
    "company": null,
    "position": null,
    "phone": "5550000104",
    "mobile": null,
    "fax": null,
    "website": null,
    "address1": null,
    "address2": null,
    "country": "MX",
    "state": null,
    "city": null,
    "zip": null,
    "facebook": null,
    "twitter": null,
    "skype": null,
    "googlePlus": null,
    "linkedin": null,
    "instagram": null,
    "comments": "",
    "referredDate": "",
    "referredByContactId": null,
    "referredAtCampaignId": null,
    "referredAtInteractionId": null,
    "lastTrackingId": null,
    "lastFingerprint": null,
    "hadDuplicateDetected": 0,
    "lastVisitEventDate": "",
    "lastConversionEventDate": "2026-09-23 09:36:04",
    "firstCallEventDate": "",
    "lastCallEventDate": "",
    "lastCallEventResult": null,
    "firstManagedCallEventDate": "",
    "lastManagedCallEventDate": "",
    "firstGoalEventDate": "",
    "lastGoalEventDate": "",
    "lastManagementResult": null,
    "lastEventDate": "2026-09-23 09:43:22",
    "lastEventType": "whatsappSendFailed",
    "lastEventId": "00000000-0000-4000-8000-000000000104|demo",
    "lastEventCampaign": "WhatsApp_Getnet",
    "createdDate": "2026-09-23 09:36:04",
    "createdOutOfHour": 0,
    "createdByCampaignId": "Campana_formulario_Meta",
    "createdByCampaignCategory": "Facebook_Ads",
    "createdByCampaignClient": "CTSolutions",
    "createdByUserId": "",
    "createdByEventType": "conversion",
    "createdByEventId": "00000000-0000-4000-9000-000000000104",
    "createdBySource": "c2c",
    "createdBySourceId": "FACEBOOK",
    "createdByClickSource": null,
    "createdByClickId": null,
    "createdByClickCampaign": null,
    "createdByClickAdGroup": null,
    "createdByClickKeyword": null,
    "createdByClickAdPosition": null,
    "AFILIACIÓN": "",
    "AGENCYNAME": "",
    "CUSADDRESS": "",
    "CUSTOMERDOCUMENTNUMBER": "",
    "CUSTOMERDOCUMENTTYPE": "",
    "Calle y Numero Comercial": "",
    "Codigo Postal Comercial": "",
    "Direccion Comercial": "",
    "Direccion Fiscal": "",
    "DÍAS DE ATRASO": "",
    "FECHA DE CREACIÓN": "",
    "Folio ISO": "",
    "Fuente": "",
    "INTORDEN": "",
    "INTQLLAMADOS": "",
    "Nombre de la empresa": "",
    "Nombre del negocio": "",
    "Representante Legal": "",
    "STATUS": "",
    "STATUSFILTRADO": "",
    "TIPO DE ACCIÓN": "",
    "TIPOLOCAL": "",
    "TMLFUENTE": "",
    "afiliacion": "",
    "amex": "",
    "calle_num_fiscal": "",
    "campaignId": "",
    "canal_atraccion": "",
    "cashback": "",
    "ciudad_comercial": "",
    "ciudad_financieros": "",
    "colonia_comercial": "",
    "colonia_financieros": "",
    "comentario_instalacion": "",
    "contacto_adicional": "",
    "cp_fiscal": "",
    "cuenta_clabe": "",
    "descripcion_actividad": "",
    "doc_acta": "",
    "doc_csf": "",
    "doc_estados_cuenta": "",
    "doc_fotografias": "",
    "doc_id_oficial": "",
    "estado_comercial": "",
    "estado_financieros": "",
    "facturacion_mensual": "",
    "fecha_afiliacion": "",
    "fecha_ot": "",
    "giro": "",
    "idRegistro": "",
    "msi_alta": "",
    "msi_otros": "",
    "msi_prosa": "",
    "num_ot": "",
    "num_terminales": "",
    "oferta_disponible": "",
    "promotor": "",
    "q1": "",
    "q2": "",
    "q3": "",
    "referencias": "",
    "rfc_comercio": "",
    "seg_agente": "",
    "seg_compromiso": "",
    "seg_descripcion": "",
    "seg_evidencia": "",
    "seg_motivo": "",
    "seg_notas": "",
    "seg_resultado": "",
    "select-calificacion": "",
    "select-subcalificacion": "",
    "terminal": "",
    "tipo_persona": "",
    "tipo_tramite": "",
    "valor_voucher": ""
  },
  {
    "id": "1000000103",
    "email": null,
    "firstname": "Pedro Gómez",
    "lastname": "",
    "score": 0,
    "stage": "lead",
    "language": null,
    "owner": null,
    "ownerTeam": null,
    "company": null,
    "position": null,
    "phone": "5550000103",
    "mobile": null,
    "fax": null,
    "website": null,
    "address1": null,
    "address2": null,
    "country": "MX",
    "state": null,
    "city": null,
    "zip": null,
    "facebook": null,
    "twitter": null,
    "skype": null,
    "googlePlus": null,
    "linkedin": null,
    "instagram": null,
    "comments": "",
    "referredDate": "",
    "referredByContactId": null,
    "referredAtCampaignId": null,
    "referredAtInteractionId": null,
    "lastTrackingId": null,
    "lastFingerprint": null,
    "hadDuplicateDetected": 0,
    "lastVisitEventDate": "",
    "lastConversionEventDate": "2026-09-23 08:53:04",
    "firstCallEventDate": "",
    "lastCallEventDate": "",
    "lastCallEventResult": null,
    "firstManagedCallEventDate": "",
    "lastManagedCallEventDate": "",
    "firstGoalEventDate": "",
    "lastGoalEventDate": "",
    "lastManagementResult": null,
    "lastEventDate": "2026-09-23 09:00:21",
    "lastEventType": "whatsappSendFailed",
    "lastEventId": "00000000-0000-4000-8000-000000000103|demo",
    "lastEventCampaign": "WhatsApp_Getnet",
    "createdDate": "2026-09-23 08:53:04",
    "createdOutOfHour": 0,
    "createdByCampaignId": "Campana_formulario_Meta",
    "createdByCampaignCategory": "Facebook_Ads",
    "createdByCampaignClient": "CTSolutions",
    "createdByUserId": "",
    "createdByEventType": "conversion",
    "createdByEventId": "00000000-0000-4000-9000-000000000103",
    "createdBySource": "c2c",
    "createdBySourceId": "FACEBOOK",
    "createdByClickSource": null,
    "createdByClickId": null,
    "createdByClickCampaign": null,
    "createdByClickAdGroup": null,
    "createdByClickKeyword": null,
    "createdByClickAdPosition": null
  },
  {
    "id": "1000000102",
    "email": null,
    "firstname": "Sofía Hernández",
    "lastname": "",
    "score": 0,
    "stage": "lead",
    "language": null,
    "owner": null,
    "ownerTeam": null,
    "company": null,
    "position": null,
    "phone": "5550000102",
    "mobile": null,
    "fax": null,
    "website": null,
    "address1": null,
    "address2": null,
    "country": "MX",
    "state": null,
    "city": null,
    "zip": null,
    "facebook": null,
    "twitter": null,
    "skype": null,
    "googlePlus": null,
    "linkedin": null,
    "instagram": null,
    "comments": "",
    "referredDate": "",
    "referredByContactId": null,
    "referredAtCampaignId": null,
    "referredAtInteractionId": null,
    "lastTrackingId": null,
    "lastFingerprint": null,
    "hadDuplicateDetected": 0,
    "lastVisitEventDate": "",
    "lastConversionEventDate": "2026-09-23 06:59:04",
    "firstCallEventDate": "",
    "lastCallEventDate": "",
    "lastCallEventResult": null,
    "firstManagedCallEventDate": "",
    "lastManagedCallEventDate": "",
    "firstGoalEventDate": "",
    "lastGoalEventDate": "",
    "lastManagementResult": null,
    "lastEventDate": "2026-09-23 07:06:19",
    "lastEventType": "whatsappSendFailed",
    "lastEventId": "00000000-0000-4000-8000-000000000102|demo",
    "lastEventCampaign": "WhatsApp_Getnet",
    "createdDate": "2026-09-23 06:59:04",
    "createdOutOfHour": 0,
    "createdByCampaignId": "Campana_formulario_Meta",
    "createdByCampaignCategory": "Facebook_Ads",
    "createdByCampaignClient": "CTSolutions",
    "createdByUserId": "",
    "createdByEventType": "conversion",
    "createdByEventId": "00000000-0000-4000-9000-000000000102",
    "createdBySource": "c2c",
    "createdBySourceId": "FACEBOOK",
    "createdByClickSource": null,
    "createdByClickId": null,
    "createdByClickCampaign": null,
    "createdByClickAdGroup": null,
    "createdByClickKeyword": null,
    "createdByClickAdPosition": null
  },
  {
    "id": "1000000101",
    "email": null,
    "firstname": "Tomás Álvarez Núñez",
    "lastname": "",
    "score": 0,
    "stage": "lead",
    "language": null,
    "owner": null,
    "ownerTeam": null,
    "company": null,
    "position": null,
    "phone": "5550000101",
    "mobile": null,
    "fax": null,
    "website": null,
    "address1": null,
    "address2": null,
    "country": "MX",
    "state": null,
    "city": null,
    "zip": null,
    "facebook": null,
    "twitter": null,
    "skype": null,
    "googlePlus": null,
    "linkedin": null,
    "instagram": null,
    "comments": "",
    "referredDate": "",
    "referredByContactId": null,
    "referredAtCampaignId": null,
    "referredAtInteractionId": null,
    "lastTrackingId": null,
    "lastFingerprint": null,
    "hadDuplicateDetected": 0,
    "lastVisitEventDate": "",
    "lastConversionEventDate": "2026-09-23 01:44:03",
    "firstCallEventDate": "",
    "lastCallEventDate": "",
    "lastCallEventResult": null,
    "firstManagedCallEventDate": "",
    "lastManagedCallEventDate": "",
    "firstGoalEventDate": "",
    "lastGoalEventDate": "",
    "lastManagementResult": null,
    "lastEventDate": "2026-09-23 01:52:14",
    "lastEventType": "whatsappSendFailed",
    "lastEventId": "00000000-0000-4000-8000-000000000101|demo",
    "lastEventCampaign": "WhatsApp_Getnet",
    "createdDate": "2026-09-23 01:44:03",
    "createdOutOfHour": 0,
    "createdByCampaignId": "Campana_formulario_Meta",
    "createdByCampaignCategory": "Facebook_Ads",
    "createdByCampaignClient": "CTSolutions",
    "createdByUserId": "",
    "createdByEventType": "conversion",
    "createdByEventId": "00000000-0000-4000-9000-000000000101",
    "createdBySource": "c2c",
    "createdBySourceId": "FACEBOOK",
    "createdByClickSource": null,
    "createdByClickId": null,
    "createdByClickCampaign": null,
    "createdByClickAdGroup": null,
    "createdByClickKeyword": null,
    "createdByClickAdPosition": null
  }
];
